# Generated by Django 4.0.2 on 2022-02-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_product_commission_alter_orderproduct_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='pos.OrderProduct', to='pos.Product'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
