# Generated by Django 4.0.2 on 2022-02-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_alter_order_customer_alter_order_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='commission',
            field=models.FloatField(default=0.0),
        ),
    ]
